#!/bin/sh

FIRST_JAR_PATH=[PATH_TO_FILE]
SECOND_JAR_PATH=[PATH_TO_FILE]
THIED_JAR_PATH=[PATH_TO_FILE]
FOURTH_JAR_PATH=[PATH_TO_FILE]

DATA_INPUT_1=[PATH_TO_soc-Livejornal1adj.txt]
DATA_INPUT_2=[PATH_TO_userdata.txt]

COMMONF_OUT_PATH=[OUT_PATH]

TOP_F_OUT_PATH_1=[TEMP_OUT_PATH]
TOP_F_OUT_PATH_2=[OUT_PATH]

DOB_OUT_PATH_1=[TEMP_OUT_PATH]
DOB_OUT_PATH_2=[OUT_PATH]

MAX_OUT_PATH_1=[TEMP_OUT_PATH]
MAX_OUT_PATH_2=[OUT_PATH]

./hadoop jar ${Q1_JAR_PATH} $DATA_INPUT_1 $COMMONF_OUT_PATH

./hadoop jar $Q2_JAR_PATH $DATA_INPUT_1 $TOP_F_OUT_PATH_1 $QTOP_F_OUT_PATH_2

./hadoop jar $Q3_JAR_PATH $DATA_INPUT_1 $DATA_INPUT_2 $DOB_OUT_PATH_1 $DOB_OUT_PATH_2

./hadoop jar $Q4_JAR_PATH $DATA_INPUT_1 $DATA_INPUT_2 $MAX_OUT_PATH_1 $MAX_OUT_PATH_2
